language: generic
sudo: required
services:
  - docker

before_cache:
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
cache:
  directories:
    - $HOME/docker
    - $HOME/.yarn-cache/

install:
  - git clone https://github.com/zilliqa/scilla

script:
  - yarn install
  - yarn build:client
  - yarn test

before_deploy:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - if [[ -d $HOME/docker ]] && [[ $(ls -1 $HOME/docker/*.tar.gz 2>/dev/null | wc -l) != 0 ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

deploy:
  provider: script
  skip_cleanup: true
  script:
    - ./scripts/deploy.sh
  on:
    branch: master

